-- Automated full seed for products table (all 18 products)
INSERT INTO products (
    slug, name, description, category, price, original_price, power_level,
    image, gallery, in_stock, stock, featured, tags, specifications, created_at, updated_at
) VALUES
('saiyan-battle-armor', 'Saiyan Battle Armor', 'Advanced light-weight Saiyan armor produced by Capsule Corp. Reinforced plating and adaptive fit.', 'Battle Gear', 299.00, 399.00, 9000, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759096578/c3_kamzog.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759096578/c3_kamzog.jpg"]', 1, 15, 1, '["KAMEHAMEHA TESTED","SAIYAN APPROVED"]', '{"weight": "2.5 kg", "defense": "9000+", "material": "Saiyan Steel"}', NOW(), NOW()),
('dragon-radar-mark-vii', 'Dragon Radar Mark VII', 'Latest model of the legendary Dragon Radar. Enhanced range and precision.', 'Technology', 899.99, 1299.99, 5000, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759610849/dragonrader_sr.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759610849/dragonrader_sr.jpg"]', 1, 8, 1, '["BULMA DESIGNED","QUANTUM ENHANCED"]', '{"range": "Global", "battery": "Solar powered"}', NOW(), NOW()),
('gravity-chamber-personal', 'Gravity Chamber (Personal)', 'Train like Vegeta with this personal gravity chamber. Adjustable up to 500x Earth gravity.', 'Training', 15999.99, 19999.99, 8500, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759168435/Firefly_-A_futuristic_fantasy_temple_standing_in_a_limitless_white_dimension._The_temple_has_921029_hgswg6.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759168435/Firefly_-A_futuristic_fantasy_temple_standing_in_a_limitless_white_dimension._The_temple_has_921029_hgswg6.jpg"]', 1, 25, 1, '["VEGETA APPROVED","EXTREME TRAINING"]', '{"size": "10m x 10m x 10m", "power": "Fusion reactor"}', NOW(), NOW()),
('senzu-bean-pack', 'Senzu Bean Pack (12 count)', 'Mystical beans that restore energy and health instantly. Pack of 12.', 'Consumables', 249.99, 299.99, 0, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759696846/scouter_noikel.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759696846/scouter_noikel.jpg"]', 1, 25, 1, '["KORIN GROWN","INSTANT HEALING"]', '{"count": "12", "expiry": "Never expires"}', NOW(), NOW()),
('power-scouter-elite', 'Power Scouter Elite', 'Advanced combat scouter with holographic display and encrypted comms.', 'Technology', 599.99, 799.99, 1500, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759608406/scouter_noike1.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759608406/scouter_noike1.jpg"]', 1, 20, 1, '["FRIEZA TECH","COMBAT READY"]', '{"range": "10km", "features": "Voice command"}', NOW(), NOW()),
('weighted-training-clothes', 'Weighted Training Clothes', 'Ultra-heavy training outfit for serious martial artists. Adjustable weights.', 'Training', 499.99, 499.99, 2000, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759696925/nimb_bgpromo.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759696925/nimb_bgpromo.jpg"]', 1, 18, 1, '["TURTLE HERMIT","STRENGTH TRAINING"]', '{"sizes": "S-XXXL", "comfort": "Breathable"}', NOW(), NOW()),
('weighted-training-clothes', 'Weighted Training Clothes', 'Ultra-heavy training outfit for serious martial artists. Adjustable weights.', 'Training', 499.99, 499.99, 2000, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759702012/Firefly___-Photorealistic_product_shot_of_Goku_s_iconic_training_gi_from_Dragon_Ball_Z_displ_365151_aeikcp.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759702012/Firefly___-Photorealistic_product_shot_of_Goku_s_iconic_training_gi_from_Dragon_Ball_Z_displ_365151_aeikcp.jpg"]', 1, 18, 1, '["TURTLE HERMIT","STRENGTH TRAINING"]', '{"sizes": "S-XXXL", "comfort": "Breathable"}', NOW(), NOW()),
('flying-nimbus-cloud', 'Flying Nimbus Cloud', 'Magical flying cloud that only the pure of heart can ride. Includes cloud care kit.', 'Transportation', 2999.99, 3999.99, 1000, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759699245/nimb_rbgqmo.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759699245/nimb_rbgqmo.jpg","https://res.cloudinary.com/dx8wt3el4/image/upload/v1759699421/nimb3_vqyt06.jpg"]', 1, 10, 1, '["PURE HEART ONLY","ECO FRIENDLY"]', '{"fuel": "None required", "speed": "Mach 1.5"}', NOW(), NOW()),
('kaio-ken-training-manual', 'Kaio-ken Training Manual', 'Comprehensive guide to the Kaio-ken technique. Includes training schedule and safety tips.', 'Training', 149.99, 199.99, 500, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759709088/Firefly-Photo.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759709088/Firefly-Photo.jpg"]', 1, 30, 1, '["KING KAI APPROVED","ADVANCED TECHNIQUE"]', '{"pages": "50", "safety": "High risk warning"}', NOW(), NOW()),
('kaio-ken-training-manual', 'Kaio-ken Training Manual', 'Comprehensive guide to the Kaio-ken technique. Includes training schedule and safety tips.', 'Training', 149.99, 199.99, 500, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1759700988/Firefly__-Photorealistic_image_of_an_advanced_Kaio-ken_training_manual_projecting_a_glowing_r_64817_trah8h.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1759700988/Firefly__-Photorealistic_image_of_an_advanced_Kaio-ken_training_manual_projecting_a_glowing_r_64817_trah8h.jpg"]', 1, 30, 1, '["KING KAI APPROVED","ADVANCED TECHNIQUE"]', '{"pages": "50", "safety": "High risk warning"}', NOW(), NOW()),
('capsule-corp-jet', 'Capsule Corp Jet', 'Personal jet for fast travel. Stealth mode, autopilot, luxury seating.', 'Vehicles', 29999.99, 34999.99, 3000, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1700000000/jet.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1700000000/jet.jpg"]', 1, 2, 1, '["STEALTH MODE","AUTOPILOT"]', '{"engine": "Fusion", "features": "Stealth, autopilot, luxury seating"}', NOW(), NOW()),
('capsule-corp-boat', 'Capsule Corp Boat', 'Luxury boat with Capsule Corp tech. Solar powered, party mode, GPS.', 'Vehicles', 7999.99, 11999.99, 1500, 'https://res.cloudinary.com/dx8wt3el4/image/upload/v1700000000/boat.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/v1700000000/boat.jpg"]', 1, 6, 1, '["SOLAR POWER","PARTY MODE"]', '{"engine": "Solar", "features": "Auto-pilot, party mode, GPS"}', NOW(), NOW()),
('house-capsule-pro', 'House Capsule Pro', 'Portable house that expands instantly. 3 bedrooms, warranty included.', 'Capsules', 4999.99, 5999.99, 2500, 'https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/house.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/house.jpg"]', 1, 8, 1, '["INSTANT HOME","CAPSULE TECH"]', '{"rooms": "3 bedrooms", "warranty": "15 years"}', NOW(), NOW()),
('vehicle-capsule-set', 'Vehicle Capsule Set', 'Collection of 5 vehicle capsules. Includes car, bike, boat, jet, and ATV.', 'Capsules', 11999.99, 19999.99, 3500, 'https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/vehicles.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/vehicles.jpg"]', 1, 5, 1, '["COMPLETE SET","ALL TERRAIN"]', '{"capsule energy": "Special", "license": "Universal"}', NOW(), NOW()),
('camping-capsule-deluxe', 'Camping Capsule Deluxe', 'Ultimate camping solution. Includes tent, kitchen, shower, and generator.', 'Capsules', 1499.99, 1999.99, 1200, 'https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/camping.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/camping.jpg"]', 1, 15, 1, '["OUTDOOR ADVENTURE","SURVIVAL READY"]', '{"setup": "Instant", "weight": "0.5kg capsule"}', NOW(), NOW()),
('workshop-capsule', 'Workshop Capsule', 'Portable workshop with all tools included. 20 sqm workspace, solar powered.', 'Capsules', 3299.99, 4299.99, 1800, 'https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/workshop.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/workshop.jpg"]', 1, 10, 1, '["MECHANIC READY","COMPLETE TOOLS"]', '{"size": "20 sqm workshop", "power": "Solar powered"}', NOW(), NOW()),
('restaurant-capsule', 'Restaurant Capsule', 'Fully equipped restaurant in a capsule. Fine dining, robot chefs, multi-cultural cuisine.', 'Capsules', 12999.99, 19999.99, 4200, 'https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/restaurant.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/restaurant.jpg"]', 1, 6, 1, '["FINE DINING","ROBOT STAFF"]', '{"cuisine": "Multi-cultural", "hygiene": "Auto-sanitize"}', NOW(), NOW()),
('laboratory-capsule', 'Laboratory Capsule', 'Portable scientific laboratory. Quantum storage, fusion reactor, safety certified.', 'Capsules', 7499.99, 9999.99, 3800, 'https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/lab.jpg', '["https://res.cloudinary.com/dx8wt3el4/image/upload/c_fill,w_400,h_400,g_center/v1700000000/lab.jpg"]', 1, 6, 1, '["RESEARCH GRADE","SAFETY CERTIFIED"]', '{"data": "Quantum storage", "power": "Fusion reactor", "safety": "Level 4 containment"}', NOW(), NOW())
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    description = VALUES(description),
    category = VALUES(category),
    price = VALUES(price),
    original_price = VALUES(original_price),
    power_level = VALUES(power_level),
    image = VALUES(image),
    gallery = VALUES(gallery),
    in_stock = VALUES(in_stock),
    stock = VALUES(stock),
    featured = VALUES(featured),
    tags = VALUES(tags),
    specifications = VALUES(specifications),
    updated_at = CURRENT_TIMESTAMP;
